apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monitoring-demo
  labels:
    app: prometheus
subjects:
  - kind: ServiceAccount
    name: monitoring-demo
    namespace: monitoring-demo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io