apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-demo
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 20s
      evaluation_interval: 10s

    rule_files:
       - /etc/rules/prometheus.rules

    scrape_configs:
    
    