apiVersion: v1
kind: Service
metadata:
  annotations: 
    prometheus.io/scrape: "true"
  name: prometheus
  namespace: monitoring-demo
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: prometheus
    protocol: TCP
    