apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring-demo
  labels:
    app: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Demo-Prometheus
      url: http://prometheus.monitoring-demo.svc.cluster.local:9090
      access: proxy
      type: prometheus
      orgId: 1

  dashboard-provider.yaml: |-
    apiVersion: 1
    providers:
    - name: 'dashboards'
      orgId: 1
      folder: ''
      folderUid: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      allowUiUpdates: false
      options:
        path: /var/lib/grafana/dashboards
      
      