apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring-demo
  labels:
    app: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Demo-Prometheus
      url: http://prometheus.monitoring-demo.svc.cluster.local:9090
      access: proxy
      type: prometheus
      orgId: 1
      
      