apiVersion: v1
kind: Service
metadata:
  annotations: 
    prometheus.io/scrape: "true"
  name: grafana
  namespace: monitoring-demo
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: grafana
    protocol: TCP