apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: stub-status 
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: nginx-exporter 
    port: 9113
    targetPort: nginx-exporter
    protocol: TCP