apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
    default.conf: |-
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;
  
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
  
          root /usr/share/nginx/html/;
          index index.html index.htm index.nginx-debian.html;
          server_name _;
  
          location / {
              try_files $uri $uri/ =404;
          }
      }
  
      server {
          listen 8080;
          location /stub_status {
              stub_status on;
          }
      }

  